matrix:
  include:
    - language: generic
      dist: trusty
      sudo: true
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t redissessionarticleapp ./app
      - docker images
      - docker tag redissessionarticleapp $DOCKER_USERNAME/redissessionarticleapp
      - docker push $DOCKER_USERNAME/redissessionarticleapp
      - docker build -t redissessionarticlenginx ./nginx
      - docker images
      - docker tag redissessionarticlenginx $DOCKER_USERNAME/redissessionarticlenginx
      - docker push $DOCKER_USERNAME/redissessionarticlenginx