matrix:
  include:
    - language: generic
      dist: trusty
      sudo: true
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t RedisSessionArticleApp ./app
      - docker images
      - docker tag RedisSessionArticleApp $DOCKER_USERNAME/RedisSessionArticleApp
      - docker push $DOCKER_USERNAME/RedisSessionArticleApp
      - docker build -t RedisSessionArticleNginx ./app
      - docker images
      - docker tag RedisSessionArticleNginx $DOCKER_USERNAME/RedisSessionArticleNginx
      - docker push $DOCKER_USERNAME/RedisSessionArticleNginx